services:

  generator-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-data:/data
    environment:
      Sync__OutputPath: /data
    restart: unless-stopped

volumes:
  static-data:
