services:

  static-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - static-data:/data
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"
      DataPath: /data
    restart: unless-stopped

volumes:
  static-data:
