services:

  static-api:
    build:
      context: ./opendatahub-static-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - static-data:/data
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"
      DataPath: /data
    restart: unless-stopped
    depends_on:
      - generator-worker

  generator-worker:
    build:
      context: ./opendatahub-static-generator-worker
      dockerfile: Dockerfile
    volumes:
      - static-data:/data
    environment:
      Sync__OutputPath: /data
    restart: unless-stopped

volumes:
  static-data:
