{{- if .Values.envSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "static-api.envSecretName" . }}
  labels:
    {{- include "static-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.envSecret }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
