services:

  generator-worker:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    volumes:
      - static-data:/data
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      Sync__OutputPath: /data
    restart: unless-stopped

volumes:
  static-data:
    name: odh-static-data
