name: CI/CD Worker

on:
  push:
    paths:
      - "opendatahub-static-generator-worker/**"      
      - ".github/workflows/main_generator.yml"
      - "infrastructure/docker-compose.worker.run.yml"
      - "infrastructure/helm/static-generator-worker/**"
      - "infrastructure/helm/static-generator-worker-test.yaml"
      - "infrastructure/helm/static-generator-worker-prod.yaml"
  pull_request:
    paths:
      - "opendatahub-static-generator-worker/**"      
      - ".github/workflows/main_generator.yml"

env:
  PROJECT_NAME: odh-static-generator-worker
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}-worker
  DOCKER_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'        
    - name: Restore dependencies
      run: dotnet restore opendatahub-static-generator.sln
    - name: Build opendatahub-static-generator Solution
      run: dotnet build opendatahub-static-generator.sln --no-restore

  # Deploy Test (Kubernetes / EKS)
  deploy-test-importer:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    needs: test
    environment: test
    concurrency: deploy-test-importer
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build and push
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          working-directory: opendatahub-static-generator-worker
          docker-compose-file: docker-compose.yml

      # https://github.com/shrink/actions-docker-registry-tag
      - name: Add an "unstable" docker tag
        uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ github.event.repository.name }}-worker
          target: ${{ env.DOCKER_TAG }}
          tags: |
            unstable

      - name: Customize static-generator-worker-test.yaml
        run: |
          yq -i '.image.repository="${{ env.DOCKER_IMAGE }}"' infrastructure/helm/static-generator-worker-test.yaml
          yq -i '.image.tag="${{ env.DOCKER_TAG }}"' infrastructure/helm/static-generator-worker-test.yaml
          yq -i '.image.pullPolicy="IfNotPresent"' infrastructure/helm/static-generator-worker-test.yaml

      - name: Deploy on cluster
        uses: noi-techpark/github-actions/helm-deploy@v3
        with:
          k8s-name: static-generator-worker
          k8s-namespace: core
          chart-path: infrastructure/helm/static-generator-worker
          values-file: infrastructure/helm/static-generator-worker-test.yaml
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1

  # Deploy Prod (Kubernetes / EKS)
  deploy-prod-importer:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/prod'
    needs: test
    environment: prod
    concurrency: deploy-prod-importer
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build and push
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          working-directory: opendatahub-static-generator-worker
          docker-compose-file: docker-compose.yml

      # https://github.com/shrink/actions-docker-registry-tag
      - name: Add a "latest" docker tag
        uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ github.event.repository.name }}-worker
          target: ${{ env.DOCKER_TAG }}
          tags: |
            latest

      - name: Customize static-generator-worker-prod.yaml
        run: |
          yq -i '.image.repository="${{ env.DOCKER_IMAGE }}"' infrastructure/helm/static-generator-worker-prod.yaml
          yq -i '.image.tag="${{ env.DOCKER_TAG }}"' infrastructure/helm/static-generator-worker-prod.yaml
          yq -i '.image.pullPolicy="IfNotPresent"' infrastructure/helm/static-generator-worker-prod.yaml

      - name: Deploy on cluster
        uses: noi-techpark/github-actions/helm-deploy@v3
        with:
          k8s-name: static-generator-worker
          k8s-namespace: core
          chart-path: infrastructure/helm/static-generator-worker
          values-file: infrastructure/helm/static-generator-worker-prod.yaml
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1
